version: '3.4'

services:
  webenrolappapi:
    image: ${DOCKER_REGISTRY-}webenrolappapi
    build:
      context: .
      dockerfile: src/WebEnrolAppApi/Dockerfile
    ports:
        - 8082:80
    environment:
        - ASPNETCORE_ENVIRONMENT = Development
