name: Imagen Docker EnrolAppApi
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     -
        name: Checkout 
        uses: actions/checkout@v2
     -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: dborborp
          password: dckr_pat_M594FMRnwqetsPNJemQcYw1oPeI
     -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
     -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./src/WebEnrolAppApi/Dockerfile
          push: true
          tags: dborborp/enrolappapi:latest
          cache-from: type=registry,ref=dborborp/enrolappapi:buildcache
          cache-to: type=registry,ref=dborborp/enrolappapi:buildcache,mode=max          
